<?php

return $marks_and_models =
    array(
        'Acura' => array('models' => array(
            'MDX',
            'RSX',
            'EL',
            'ILX',
            'Integra',
            'MDX',
            'NSX',
            'RDX',
            'RL',
            'RLX',
            'RSX',
            'TL',
            'TLX',
            'TSX',
            'ZDX',
        )
        ),
        'Alfa Romeo' => array('models' => array(
            '146',
            '147',
            '147 GTA',
            '156',
            '156 GTA',
            '159',
            '166',
            '4C',
            '8C Competizione',
            'Brera',
            'Giulia',
            'Giulietta',
            'GT',
            'GTV',
            'MiTo',
            'Spider',
            'Stelvio',
        )
        ),
        'Aston Martin' => array('models' => array(
            'Cygnet',
            'DB11',
            'DB9',
            'DBS',
            'DBS Violante',
            'DBX',
            'Rapide',
            'V12 Vantage',
            'V8 Vantage',
            'Valkyrie',
            'Vanquish',
            'Virage',
            'Zagato Coupe'
        )
        ),
        'Audi' => array('models' => array(
            'A1',
            'A2',
            'A3',
            'A4',
            'A4 Allroad Quattro',
            'A5',
            'A6',
            'A7',
            'A8',
            'Allroad',
            'E-Tron',
            'Q2',
            'Q3',
            'Q5',
            'Q7',
            'Q8',
            'R8',
            'RS Q3',
            'RS3',
            'RS4',
            'RS5',
            'RS6',
            'RS7',
            'S3',
            'S4',
            'S5',
            'S6',
            'S7',
            'S8',
            'SQ2',
            'SQ5',
            'SQ7',
            'SQ8',
            'TT',
            'TT RS',
            'TTS',
        )
        ),
        'Bently' => array('models' => array(
            'Arnage',
            'Azure',
            'Bentayga',
            'Brooklands',
            'Continental',
            'Continental Flying Spur',
            'Continental GT',
            'Flying Spur',
            'Mulsanne',

        )
        ),
        'BMW' => array('models' => array(
            '1 series',
            '2 series',
            '3 series',
            '4 series',
            '5 series',
            '6 series',
            '7 series',
            '8 series',
            'i3',
            'i8',
            'M2',
            'M3',
            'M4',
            'M5',
            'M6',
            'X1',
            'X2',
            'X3',
            'X3 M',
            'X4',
            'X4 M',
            'X5',
            'X5 M',
            'X6',
            'X6 M',
            'X7',
            'Z3',
            'Z4',
            'Z8',

        )
        ),
        'Brilliance' => array('models' => array(
            'H230',
            'V3',
            'V5',

        )
        ),
        'Bugatti' => array('models' => array(
            'Veyron',
        )
        ),
        'Buick' => array('models' => array(
            'Century',
            'Enclave',
            'Envision',
            'La Crosse',
            'Le Sabre',
            'Lucerne',
            'Park Avenue',
            'Rainier',
            'Regal',
            'Rendezvouz',
            'Terraza',
            'Verano',

        )
        ),
        'Cadillac' => array('models' => array(
            'ATS',
            'ATS-V',
            'BLS',
            'CT6',
            'CTS',
            'De Ville',
            'DTS',
            'Eldorado',
            'ELR',
            'Escalade',
            'Seville',
            'SRX',
            'STS',
            'XLR',
            'XT4',
            'XT5',
            'XT6',
            'XTS',
        )
        ),
        'Changan' => array('models' => array(
            'CS35',
            'CS35 Plus',
            'CS55',
            'CS75',
            'CS95',
            'Eado',
            'Raeton',

        )
        ),
        'Chery' => array('models' => array(
            'Amulet',
            'Arrizo 7',
            'Bonus',
            'Bonus 3',
            'CrossEastar',
            'Eastar',
            'Fora',
            'IndiS',
            'Kimo',
            'M11',
            'QQ',
            'QQ6',
            'Tiggo',
            'Tiggo 3',
            'Tiggo 4',
            'Tiggo 5',
            'Tiggo 7',
            'Tiggo 8',
            'Very',

        )
        ),
        'Chevrolet' => array('models' => array(
            'Astro',
            'Avalanche',
            'Aveo',
            'Blazer',
            'Camaro',
            'Captiva',
            'Cavalier',
            'Cobalt',
            'Colorado',
            'Corvette',
            'Cruze',
            'Epica',
            'Equinox',
            'Express',
            'HHR',
            'Impala',
            'Lacetti',
            'Lanos',
            'Malibu',
            'Monte Carlo',
            'Niva',
            'Orlando',
            'Rezzo',
            'Silverado',
            'Silverado 2500 HD',
            'Spark',
            'SSR',
            'Suburban',
            'Tahoe',
            'TrailBlazer',
            'Traverse',
            'Trax',
            'Uplander',
            'Venture',

        )
        ),
        'Chrysler' => array('models' => array(
            '200',
            '300',
            '300M',
            'Aspen',
            'Concorde',
            'Crossfire',
            'Grand Voyager',
            'Pacifica',
            'PT Cruiser',
            'Sebring',
            'Town & Country',
            'Voyager',

        )
        ),
        'Citroen' => array('models' => array(
            'Berlingo',
            'C-Crosser',
            'C-Elysee',
            'C1',
            'C2',
            'C3',
            'C3 Aircross',
            'C3 Picasso',
            'C3 Pluriel',
            'C4',
            'C4 Aircross',
            'C4 Cactus',
            'C4 Picasso',
            'C5',
            'C6',
            'C8',
            'DS 7 Crossback',
            'DS3',
            'DS4',
            'DS5',
            'Grand C4 Picasso',
            'Jumpy',
            'Nemo',
            'Saxo',
            'Spacetourer',
            'Xsara',
            'Xsara Picasso',

        )
        ),
        'Daewoo' => array('models' => array(
            'Evanda',
            'Kalos',
            'Leganza',
            'Magnus',
            'Matiz',
            'Nexia',
            'Nubira',

        )
        ),
        'Daihatsu' => array('models' => array(
            'Applause',
            'Cast',
            'Copen',
            'Cuore',
            'Gran Move',
            'Luxio',
            'Materia',
            'Mebius',
            'Move',
            'Rocky',
            'Sirion',
            'Terios',
            'Trevis',
            'YRV',

        )
        ),
        'Datsun' => array('models' => array(
            'mi-DO',
            'on-DO'

        )
        ),
        'Dodge' => array('models' => array(
            'Avenger',
            'Caliber',
            'Caliber SRT4',
            'Caravan',
            'Challenger',
            'Charger',
            'Dakota',
            'Dart',
            'Durango',
            'Intrepid',
            'Journey',
            'Magnum',
            'Neon',
            'Nitro',
            'Ram 1500',
            'Ram 2500',
            'Ram 3500',
            'Ram SRT10',
            'Stratus',
            'Viper',

        )
        ),
        'Dongfeng' => array('models' => array(
            '580',
            'A30',
            'AX7',
            'H30 Cross',
        )
        ),
        'FAW' => array('models' => array(
            'Besturn B30',
            'Besturn B50',
            'Besturn X40',
            'Besturn X80',
            'Oley',
            'Vita',
        )
        ),
        'Ferrari' => array('models' => array(
            '348',
            '360',
            '456',
            '458',
            '488',
            '512',
            '550',
            '575M',
            '599 GTB Fiorano',
            '599 GTO',
            '612',
            '812',
            'California',
            'California T',
            'Challenge Stradale',
            'Enzo',
            'F12',
            'F355',
            'F430',
            'F50',
            'F512 M',
            'FF',
            'GTC4 Lusso',
            'LaFerrari',

        )
        ),
        'FIAT' => array('models' => array(
            '124 Spider',
            '500',
            '500L',
            '500X',
            'Albea',
            'Brava',
            'Bravo',
            'Coupe',
            'Croma',
            'Doblo',
            'Ducato',
            'Freemont',
            'Grande Punto',
            'Idea',
            'Linea',
            'Marea',
            'Multipla',
            'Palio',
            'Panda',
            'Panda 4x4',
            'Punto',
            'Qubo',
            'Sedici',
            'Siena',
            'Stilo',
            'Strada',
            'Tipo',
            'Ulysse',
        )
        ),
        'Ford' => array('models' => array(
            'B-Max',
            'C-Max',
            'Cougar',
            'Crown Victoria',
            'EcoSport',
            'Edge',
            'Escape',
            'Excursion',
            'Expedition',
            'Explorer',
            'Explorer Sport Trac',
            'F-150',
            'F-250',
            'F-350',
            'Falcon',
            'Fiesta',
            'Five Hundred',
            'Flex',
            'Focus',
            'Focus Active',
            'Freestar',
            'Freestyle',
            'Fusion',
            'Galaxy',
            'Ka',
            'Kuga',
            'Maverick',
            'Mondeo',
            'Mustang',
            'Mustang Shelby GT350',
            'Mustang Shelby GT500',
            'Puma',
            'Ranger',
            'S-Max',
            'Taurus',
            'Taurus X',
            'Thunderbird',
            'Tourneo Connect',
            'Transit',
            'Transit Connect',
        )
        ),
        'Geely' => array('models' => array(
            'Atlas',
            'Coolray',
            'Emgrand 7',
            'Emgrand EC7',
            'Emgrand GS',
            'Emgrand X7',
            'GC9',
            'GРЎ6',
            'MK',
            'Otaka',
            'Vision',
        )
        ),
        'Great Wall' => array('models' => array()
        ),
        'Genesis' => array('models' => array(
            'G70',
            'G80',
            'G90',
        )
        ),
        'GMC' => array('models' => array(
            'Acadia',
            'Canyon',
            'Envoy',
            'Sierra 1500',
            'Sierra 2500',
            'Terrain',
            'Yukon',

        )
        ),
        'Great Wall' => array('models' => array(
            'Cowry',
            'Deer',
            'Hover',
            'Hover M2',
            'Pegasus',
            'Peri',
            'Safe',
            'Sailor',
            'Sing',
            'Socool',
            'Wingle',
        )
        ),
        'Haval' => array('models' => array(
            'F7',
            'H4',
            'H6',
            'H9',
        )
        ),
        'Holden' => array('models' => array(
            'Commodore',
        )
        ),
        'Honda' => array('models' => array(
            'Accord',
            'Amaze',
            'City',
            'Civic',
            'CR-V',
            'CR-Z',
            'Crosstour',
            'Element',
            'Fit',
            'FR-V',
            'HR-V',
            'HR-V II (GJ)',
            'Insight',
            'Jade',
            'Jazz',
            'Legend',
            'Odyssey',
            'Pilot',
            'Prelude',
            'Ridgeline',
            'S2000',
            'Shuttle',
            'Stream',
            'Vezel',
        )
        ),
        'Hummer' => array('models' => array(
            'H1',
            'H2',
            'H3',
        )
        ),
        'Hyundai' => array('models' => array(
            'H1',
            'H2',
            'H3',
            'Accent',
            'Atos Prime',
            'Azera',
            'Centennial',
            'Creta',
            'Elantra',
            'Entourage',
            'Eon',
            'Equus',
            'Galloper',
            'Genesis',
            'Genesis Coupe',
            'Getz',
            'Grandeur',
            'H-1',
            'i10',
            'i20',
            'i30',
            'i30 N',
            'i40',
            'Ioniq',
            'ix20',
            'ix35',
            'Kona',
            'Matrix',
            'Palisade',
            'Porter',
            'Santa Fe',
            'Solaris',
            'Sonata',
            'Terracan',
            'Trajet',
            'Tucson',
            'Veloster',
            'Veracruz',
            'Verna',
            'Xcent',
            'XG',

        )
        ),
        'Infiniti' => array('models' => array(
            'EX',
            'FX',
            'G',
            'I35',
            'JX',
            'M',
            'Q30',
            'Q40',
            'Q45',
            'Q50',
            'Q60',
            'Q70',
            'QX30',
            'QX4',
            'QX50',
            'QX56',
            'QX60',
            'QX70',
            'QX80',
        )
        ),
        'Isuzu' => array('models' => array(
            'Ascender',
            'Axiom',
            'D-Max',
            'D-Max Rodeo',
            'I280',
            'I290',
            'I350',
            'I370',
            'Rodeo',
            'Trooper',
            'VehiCross',
        )
        ),
        'Iveco' => array('models' => array(
            'Daily',
        )
        ),
        'Jaguar' => array('models' => array(
            'E-Pace',
            'F-Pace',
            'F-Type',
            'I-Pace',
            'S-Type',
            'X-Type',
            'XE',
            'XF',
            'XJ',
            'XK/XKR',
        )
        ),
        'Jeep' => array('models' => array(
            'Cherokee',
            'Commander',
            'Compass',
            'Gladiator',
            'Grand Cherokee',
            'Liberty',
            'Patriot',
            'Renegade',
            'Wrangler',
        )
        ),
        'KIA' => array('models' => array(
            'Carens',
            'Carnival',
            'Ceed',
            'Cerato',
            'Clarus',
            'Forte',
            'K900',
            'Magentis',
            'Mohave',
            'Niro',
            'Opirus',
            'Optima',
            'Picanto',
            'ProCeed',
            'Quoris',
            'Ray',
            'Rio',
            'Rio X-Line',
            'Seltos',
            'Shuma',
            'Sorento',
            'Sorento Prime',
            'Soul',
            'Spectra',
            'Sportage',
            'Stinger',
            'Stonic',
            'Telluride',
            'Venga',
        )
        ),
        'Lamborghini' => array('models' => array(
            'Aventador',
            'Centenario',
            'Diablo',
            'Gallardo',
            'Huracan',
            'Murcielago',
            'Reventon',
            'Urus',

        )
        ),
        'Lancia' => array('models' => array(
            'Delta',
            'Lybra',
            'Musa',
            'Phedra',
            'Thema',
            'Thesis',
            'Ypsilon',

        )
        ),
        'Land Rover' => array('models' => array(
            'Defender',
            'Discovery',
            'Discovery Sport',
            'Evoque',
            'Freelander',
            'Range Rover',
            'Range Rover Sport',
            'Range Rover Velar',

        )
        ),
        'Lexus' => array('models' => array(
            'CT',
            'ES',
            'GS',
            'GX',
            'HS',
            'IS',
            'LC',
            'LFA',
            'LS',
            'LX',
            'NX',
            'RC',
            'RX',
            'SC',
            'UX',

        )
        ),
        'LIFAN' => array('models' => array(
            'Breez',
            'Cebrium',
            'Celliya',
            'Smily',
            'Solano',
            'X50',
            'X60',

        )
        ),
        'Lincoln' => array('models' => array(
            'Aviator',
            'Corsair',
            'Mark LT',
            'MKC',
            'MKS',
            'MKT',
            'MKX',
            'MKZ',
            'Navigator',
            'Town Car',
            'Zephyr',

        )
        ),
        'Lotus' => array('models' => array(
            'Elise',
            'Europa S',
            'Evora',
            'Exige',
        )
        ),
        'Marussia' => array('models' => array(
            'B1',
            'B2',
        )
        ),
        'Maserati' => array('models' => array(
            '3200 GT',
            'Ghibli',
            'Gran Cabrio',
            'Gran Turismo ',
            'Gran Turismo S',
            'Levante',
            'Quattroporte',
            'Quattroporte S',
        )
        ),
        'Maybach' => array('models' => array(
            '57',
            '57 S',
            '62',
            '62 S',
            'Landaulet',
        )
        ),
        'Mazda' => array('models' => array(
            '2',
            '3',
            '323',
            '5',
            '6',
            '626',
            'B-Series',
            'BT-50',
            'CX-3',
            'CX-5',
            'CX-7',
            'CX-9',
            'MPV',
            'MX-5',
            'Premacy',
            'RX-7',
            'RX-8',
            'Tribute',
        )
        ),
        'McLaren' => array('models' => array(
            '540C',
            '570S',
            '600LT',
            '650S',
            '675LT',
            '720S',
            'MP4-12C',
            'P1',
        )
        ),
        'Mercedes-Benz' => array('models' => array(
            'A-class',
            'AMG GT',
            'AMG GT 4-Door',
            'B-class',
            'C-class',
            'C-class Sport Coupe',
            'CL-class',
            'CLA-class',
            'CLC-class ',
            'CLK-class',
            'CLS-class',
            'E-class',
            'E-class Coupe',
            'EQC',
            'G-class',
            'GL-class',
            'GLA-class',
            'GLB-class',
            'GLC-class',
            'GLC-class Coupe',
            'GLE-class',
            'GLE-class Coupe',
            'GLK-class',
            'GLS-class',
            'M-class',
            'R-class',
            'S-class',
            'S-class Cabrio',
            'S-class Coupe',
            'SL-class',
            'SLK-class',
            'SLR-class',
            'SLS AMG',
            'Sprinter',
            'Vaneo',
            'Viano',
            'Vito',
            'X-class',
        )
        ),
        'Mercury' => array('models' => array(
            'Grand Marquis',
            'Mariner',
            'Milan',
            'Montego',
            'Monterey',
            'Mountaineer',
            'Sable',

        )
        ),
        'MG' => array('models' => array(
            'TF',
            'XPower SV',
            'ZR',
            'ZS',
            'ZT',
            'ZT-T',
        )
        ),
        'MINI' => array('models' => array(
            'Clubman',
            'Clubman S',
            'Clubvan',
            'Cooper',
            'Cooper Cabrio',
            'Cooper S',
            'Cooper S Cabrio',
            'Cooper S Countryman All4',
            'Countryman',
            'One',
        )
        ),
        'Mitsubishi' => array('models' => array(
            '3000 GT',
            'ASX',
            'Carisma',
            'Colt',
            'Dignity',
            'Eclipse',
            'Eclipse Cross',
            'Endeavor',
            'Galant',
            'Grandis',
            'i-MiEV',
            'L200',
            'Lancer',
            'Lancer Evo',
            'Mirage',
            'Outlander',
            'Outlander XL',
            'Pajero',
            'Pajero Pinin',
            'Pajero Sport',
            'Raider',
            'Space Gear',
            'Space Runner',
            'Space Star',
        )
        ),
        'Nissan' => array('models' => array(
            '350Z',
            '370Z',
            'Almera',
            'Almera Classic',
            'Almera Tino',
            'Altima',
            'Armada',
            'Bluebird Sylphy',
            'GT-R',
            'Juke',
            'Leaf',
            'Maxima',
            'Micra',
            'Murano',
            'Navara',
            'Note',
            'NP300',
            'Pathfinder',
            'Patrol',
            'Primera',
            'Qashqai',
            'Qashqai+2',
            'Quest',
            'Rogue',
            'Sentra',
            'Skyline',
            'Sylphy',
            'Teana',
            'Terrano',
            'Tiida',
            'Titan',
            'Titan XD',
            'X-Trail',
            'XTerra',
            'Z',
        )
        ),
        'Noble' => array('models' => array(
            'M600',
        )
        ),
        'Opel' => array('models' => array(
            'Adam',
            'Agila',
            'Antara',
            'Astra',
            'Astra GTS',
            'Cascada',
            'Combo',
            'Corsa',
            'Corsa OPC',
            'Crossland X',
            'Frontera',
            'Grandland X',
            'Insignia',
            'Insignia OPC',
            'Karl',
            'Meriva',
            'Mokka',
            'Omega',
            'Signum',
            'Speedster',
            'Tigra',
            'Vectra',
            'Vivaro',
            'Zafira',
            'Zafira Tourer',
        )
        ),
        'Peugeot' => array('models' => array(
            '1007',
            '107',
            '108',
            '2008',
            '206',
            '207',
            '208',
            '3008',
            '301',
            '307',
            '308',
            '4007',
            '4008',
            '406',
            '407',
            '408',
            '5008',
            '508',
            '607',
            '807',
            'Boxer',
            'Partner',
            'RCZ Sport',
        )
        ),
        'Plymouth' => array('models' => array(
            'Road Runner',
        )
        ),
        'Pontiac' => array('models' => array(
            'Aztec',
            'Bonneville',
            'Firebird',
            'G5 Pursuit',
            'G6',
            'G8',
            'Grand AM',
            'Grand Prix',
            'GTO',
            'Montana',
            'Solstice',
            'Sunfire',
            'Torrent',
            'Vibe',
        )
        ),
        'Porsche' => array('models' => array(
            '718 Boxster',
            '718 Cayman',
            '911',
            'Boxster',
            'Cayenne',
            'Cayman',
            'Macan',
            'Panamera',
            'Taycan',

        )
        ),
        'Ravon' => array('models' => array(
            'Gentra',
        )
        ),
        'Renault' => array('models' => array(
            'Arkana',
            'Avantime',
            'Captur',
            'Clio',
            'Duster',
            'Duster Oroch',
            'Espace',
            'Fluence',
            'Grand Scenic',
            'Kadjar',
            'Kangoo',
            'Kaptur',
            'Koleos',
            'Laguna',
            'Latitude',
            'Logan',
            'Master',
            'Megane',
            'Modus',
            'Sandero',
            'Sandero Stepway',
            'Scenic',
            'Symbol',
            'Talisman',
            'Trafic',
            'Twingo',
            'Twizy',
            'Vel Satis',
            'Wind',
            'Zoe',
        )
        ),
        'Rolls-Royce' => array('models' => array(
            'Cullinan',
            'Dawn',
            'Ghost',
            'Phantom',
            'Wraith',
        )
        ),
        'Rover' => array('models' => array(
            '25',
            '400',
            '45',
            '600',
            '75',
            'Streetwise',
        )
        ),
        'Saab' => array('models' => array(
            '9-2x',
            '9-3',
            '9-4x',
            '9-5',
            '9-7x',
        )
        ),
        'Saturn' => array('models' => array(
            'Aura',
            'Ion',
            'LW',
            'Outlook',
            'Sky',
            'Vue',
        )
        ),
        'Skion' => array('models' => array(
            'FR-S',
            'tC',
            'xA',
            'xB',
            'xD',
        )
        ),
        'Seat' => array('models' => array(
            'Alhambra',
            'Altea',
            'Altea Freetrack',
            'Altea XL',
            'Arosa',
            'Ateca',
            'Cordoba',
            'Exeo',
            'Ibiza',
            'Leon',
            'Mii',
            'Toledo',
        )
        ),
        'Skoda' => array('models' => array(
            'Citigo',
            'Fabia',
            'Felicia',
            'Kamiq',
            'Karoq',
            'Kodiaq',
            'Octavia',
            'Octavia Scout',
            'Octavia Tour',
            'Praktik',
            'Rapid',
            'Rapid Spaceback (NH1)',
            'Roomster',
            'Superb',
            'Yeti',
        )
        ),
        'Smart' => array('models' => array(
            'Forfour',
            'Fortwo',
            'Roadster',
        )
        ),
        'SsangYong' => array('models' => array(
            'Actyon',
            'Actyon Sports',
            'Chairman',
            'Korando',
            'Kyron',
            'Musso',
            'Musso Sport',
            'Rexton',
            'Rodius',
            'Stavic',
            'Tivoli',
            'XLV',
        )
        ),
        'Subaru' => array('models' => array(
            'Ascent',
            'Baja',
            'Crosstrack',
            'Exiga',
            'Forester',
            'Impreza',
            'Justy',
            'Legacy',
            'Levorg',
            'Outback',
            'Traviq',
            'Tribeca',
            'WRX',
            'XV',
        )
        ),
        'Suzuki' => array('models' => array(
            'Alto',
            'Baleno',
            'Celerio',
            'Ciaz',
            'Grand Vitara',
            'Grand Vitara XL7',
            'Ignis',
            'Jimny',
            'Kizashi',
            'Liana',
            'Splash',
            'Swift',
            'SX4',
            'Vitara',
            'Wagon R',
            'Wagon R+',
        )
        ),
        'Toyota' => array('models' => array(
            '4Runner',
            'Alphard',
            'Auris',
            'Avalon',
            'Avensis',
            'Avensis Verso',
            'Aygo',
            'C-HR',
            'Caldina',
            'Camry',
            'Celica',
            'Corolla',
            'Corolla Verso',
            'FJ Cruiser',
            'Fortuner',
            'GT 86',
            'Hiace',
            'Highlander',
            'Hilux',
            'iQ',
            'ist',
            'Land Cruiser',
            'Land Cruiser Prado',
            'Mark II',
            'Mirai',
            'MR2',
            'Picnic',
            'Previa',
            'Prius',
            'RAV4',
            'Sequoia',
            'Sienna',
            'Supra',
            'Tacoma',
            'Tundra',
            'Venza',
            'Verso',
            'Vitz',
            'Yaris',
            'Yaris Verso',
        )
        ),
        'Tesla' => array('models' => array(
            'Model 3',
            'Model S',
            'Model X',
            'Model Y',
        )
        ),
        'Volkswagen' => array('models' => array(
            'Amarok',
            'Arteon',
            'Beetle',
            'Bora',
            'Caddy',
            'CC',
            'Crafter',
            'CrossGolf',
            'CrossPolo',
            'CrossTouran',
            'Eos',
            'Fox',
            'Golf',
            'Jetta',
            'Lupo',
            'Multivan',
            'New Beetle',
            'Passat',
            'Passat CC',
            'Phaeton',
            'Pointer',
            'Polo',
            'Routan',
            'Scirocco',
            'Sharan',
            'T-Roc',
            'Teramont',
            'Tiguan',
            'Touareg',
            'Touran',
            'Transporter',
            'Up',
        )
        ),
        'Volvo' => array('models' => array(
            'C30',
            'C70',
            'C70 Convertible',
            'C70 Coupe',
            'S40',
            'S60',
            'S70',
            'S80',
            'S90',
            'V40',
            'V50',
            'V60',
            'V70',
            'V90',
            'XC40',
            'XC60',
            'XC70',
            'XC90',
        )
        ),
        'ВАЗ (LADA)' => array('models' => array(
            '2101-2107',
            '2108',
            '2110',
            '2113',
            '4x4 Urban',
            'Granta',
            'Largus',
            'Largus Cross',
            'Vesta Cross',
            'Vesta Sport',
            'Vesta SW',
            'XRay',
            'XRay Cross',
        )
        ),
        'ГАЗ' => array('models' => array(
            '3102',
            '31105',
            'Siber',
            'Sobol',
        )
        ),
        'УАЗ' => array('models' => array(
            'Pickup',
        )
        ),
    );